# Local PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=admin
spring.datasource.password=password

# Local Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.url=